# Generated by Django 2.2.4 on 2019-08-14 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 14, 20, 45, 26, 880214), verbose_name='date created'),
        ),
    ]
