# Generated by Django 2.2.4 on 2019-08-14 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190814_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.IntegerField()),
                ('gender', models.IntegerField()),
                ('question', models.IntegerField()),
                ('answer', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2019, 8, 14, 22, 28, 12, 539453), verbose_name='date created')),
            ],
        ),
        migrations.DeleteModel(
            name='users',
        ),
    ]
