# Generated by Django 2.2.4 on 2019-08-15 15:25

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190815_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 15, 20, 55, 35, 914601), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=8, unique=True),
        ),
    ]
