# Generated by Django 2.2.4 on 2019-08-15 15:35

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190815_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 15, 21, 5, 55, 223878), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
